### PR TITLE
Outline label for columns

### PR DESCRIPTION
**Pull request by yfakariya**
This PR is supplement of #28, and uses new function which was added in #30.

I knew that I could retrieve labels of columns after #28, so I implemented label support for columns in addition to headlines(chapters).

### CODE REVIEW

**Comment by yfakariya** [comment]
I've added a fix or this PR... sorry.

**Comment by atsushieno** [comment]
Thanks! But I have a Q on the changes: So, after this PR are `//[column]`s with `{label} actual column title` supposed to be listed as `actual column title` on the OUTLINE list, skipping `{label}` part? When I add label to some `//column` line, the item simply disappears from the list. It looks like the current behavior (not like a regression in the PR), but then I wonder what I could try to verify the changes.

**Comment by yfakariya** [comment]
After this PR, `==[column]{LABEL} CAPTION` should be shown as `{LABEL} CAPTION`.
I've just found that I carelessly delete `[column]` prefix from the output, so I guess you lost column outline because it looked as headline (chapter). It is not an intentional behavior, just a bug of this PR, so I will fix soon.

Summary:
* Before this PR: `[column] CAPTION` (without the label content)
* After this PR: `{LABEL} CAPTION` (the label content have been appeared, but the prefix have been disappeared)
* My intent: `[column] {LABEL} CAPTION` (with the prefix and the label content)

**Comment by atsushieno** [comment]
Is this in good state now?

**Comment by yfakariya** [comment]
Yes, I fixed as I understood.

**Comment by atsushieno** [comment]
Okay, so after the changes this is the expected behavior: 
image

I'm not sure if having `{label}` on the OUTLINE view is better, but probably chances are that more than one column can look identical without labels, maybe often, and maybe such document structure is not necessarily ugly, or it's very helpful to have bare labels on the OUTLINE view in spite of looking ugly?

Let me apply the PR anyways. Thanks!

**Pull request merged**
